#	2012-10-16
#
#	Tim Fox <tfox@rfschools.com> 2011
#	Mac OS X Systems Administrator
#
#
#	Luggage makefile for "dropping" in ManagedInstall.plist

include /usr/local/share/luggage/luggage.make

TITLE=Managed_Install_Prefs_10_8_admin
REVERSE_DOMAIN=com.rfschools
PAYLOAD=pack-Library-Preferences-ManagedInstalls.plist
PACKAGE_VERSION=1.0
